pluginManagement {
	repositories {
		maven {
			url = "https://maven.fabricmc.net/"
			name = "Fabric"
		}
		maven {
			url = "https://maven.neoforged.net/releases"
			name = "NeoForged"
		}
		gradlePluginPortal()
	}
	plugins {
		id("fabric-loom") version "1.10.1"
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = "TechRebornForNeoForge1.21.1"

include("RebornCore")
include("migration-tool")
